<?php

declare(strict_types=1);

namespace Hn\McpServer\Http;

use Hn\McpServer\Service\WorkspaceContextService;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\UploadedFileInterface;
use TYPO3\CMS\Core\Authentication\BackendUserAuthentication;
use TYPO3\CMS\Core\Context\Context;
use TYPO3\CMS\Core\Context\FileProcessingAspect;
use TYPO3\CMS\Core\Context\UserAspect;
use TYPO3\CMS\Core\Context\WorkspaceAspect;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Http\Response;
use TYPO3\CMS\Core\Http\Stream;
use TYPO3\CMS\Core\Localization\LanguageServiceFactory;
use TYPO3\CMS\Core\Resource\Enum\DuplicationBehavior;
use TYPO3\CMS\Core\Resource\Index\Indexer;
use TYPO3\CMS\Core\Resource\ProcessedFile;
use TYPO3\CMS\Core\Resource\ResourceFactory;
use TYPO3\CMS\Core\Resource\Security\SvgSanitizer;
use TYPO3\CMS\Core\Core\SystemEnvironmentBuilder;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * HTTP endpoint for direct file uploads using pre-signed tokens
 *
 * This endpoint receives files uploaded via curl from Claude Code.
 * Authentication is done via one-time tokens generated by GetUploadCredentialsTool.
 *
 * Route: POST /mcp/upload
 * Auth: Authorization: Bearer {token}
 */
class FileUploadEndpoint
{
    use CorsHeadersTrait;

    public function __invoke(ServerRequestInterface $request): ResponseInterface
    {
        // Handle CORS preflight
        if ($request->getMethod() === 'OPTIONS') {
            return $this->handlePreflightRequest();
        }

        // Only POST allowed
        if ($request->getMethod() !== 'POST') {
            return $this->jsonError('Method not allowed. Use POST.', 405);
        }

        // Extract Bearer token
        $token = $this->extractBearerToken($request);
        if ($token === null) {
            return $this->jsonError('Missing Authorization header. Use: Authorization: Bearer {token}', 401);
        }

        // Hash token for lookup
        $tokenHash = hash('sha256', $token);

        // Atomic token consumption
        $tokenData = $this->consumeToken($tokenHash);
        if ($tokenData === null) {
            return $this->jsonError('Invalid, expired, or already used token.', 401);
        }

        // Validate BE user is still active
        $beUserUid = (int)$tokenData['be_user_uid'];
        if (!$this->isUserActive($beUserUid)) {
            return $this->jsonError('User account is disabled or deleted.', 403);
        }

        // Set up BE user context
        $this->setupBackendUserContext($beUserUid);

        // Set application type attribute for TYPO3 v13+ (required for FAL operations)
        $request = $request->withAttribute('applicationType', SystemEnvironmentBuilder::REQUESTTYPE_BE);

        // Set global request for TYPO3 internal services that expect it
        $GLOBALS['TYPO3_REQUEST'] = $request;

        // Disable deferred image processing — DeferredBackendImageProcessor requires a full
        // backend session with CSRF tokens, which this endpoint doesn't have (Bearer token only).
        // Setting deferProcessing=false routes image processing through LocalImageProcessor instead.
        $context = GeneralUtility::makeInstance(Context::class);
        $context->setAspect('fileProcessing', new FileProcessingAspect(false));

        $folder = (string)$tokenData['folder'];
        $filename = (string)$tokenData['filename'];
        $maxSize = (int)$tokenData['max_size'];

        // Check Content-Length header (if present)
        $contentLength = $request->getHeaderLine('Content-Length');
        if ($contentLength !== '' && (int)$contentLength > $maxSize) {
            return $this->jsonError(sprintf(
                'File too large. Content-Length: %d bytes exceeds max: %d bytes.',
                (int)$contentLength,
                $maxSize
            ), 413);
        }

        // Get uploaded file
        $uploadedFiles = $request->getUploadedFiles();
        $uploadedFile = $uploadedFiles['file'] ?? null;
        if (!$uploadedFile instanceof UploadedFileInterface) {
            return $this->jsonError('Missing "file" field in form data. Use: curl -F "file=@path"', 400);
        }

        // Check PHP upload errors (D11: handle UPLOAD_ERR_INI_SIZE etc)
        $uploadError = $uploadedFile->getError();
        if ($uploadError !== UPLOAD_ERR_OK) {
            return $this->handleUploadError($uploadError);
        }

        // Check actual file size (for chunked encoding where Content-Length was absent)
        $actualSize = $uploadedFile->getSize();
        if ($actualSize > $maxSize) {
            return $this->jsonError(sprintf(
                'File too large: %d bytes (max: %d bytes).',
                $actualSize,
                $maxSize
            ), 413);
        }

        // Resolve folder and check permissions
        $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
        try {
            $folderObject = $resourceFactory->getFolderObjectFromCombinedIdentifier($folder);
        } catch (\Exception $e) {
            return $this->jsonError('Target folder no longer exists: ' . $e->getMessage(), 400);
        }

        // Re-check write permission (may have changed since token creation)
        if (!$folderObject->checkActionPermission('write')) {
            return $this->jsonError('Write permission revoked for folder.', 403);
        }

        $storage = $folderObject->getStorage();

        // Validate file extension against storage allowed types
        $extension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
        $allowedExtensions = $this->getAllowedExtensions($storage);
        if ($allowedExtensions !== null && !in_array($extension, $allowedExtensions, true)) {
            return $this->jsonError(sprintf(
                'File type ".%s" not allowed. Allowed: %s',
                $extension,
                implode(', ', $allowedExtensions)
            ), 415);
        }

        // MIME-type validation (D9: defense in depth)
        $detectedMimeType = $this->detectMimeType($uploadedFile);
        if (!$this->isMimeTypeAllowedForExtension($detectedMimeType, $extension)) {
            return $this->jsonError(sprintf(
                'MIME type mismatch. File extension is ".%s" but content is "%s".',
                $extension,
                $detectedMimeType
            ), 415);
        }

        // SVG sanitization
        if ($extension === 'svg') {
            $this->sanitizeSvgUpload($uploadedFile);
        }

        // Move uploaded file to temp location for FAL processing
        $tempPath = GeneralUtility::tempnam('mcp_http_upload_');
        try {
            $uploadedFile->moveTo($tempPath);

            // Check for existing file (CANCEL mode = abort)
            if ($folderObject->hasFile($filename)) {
                return $this->jsonError(sprintf(
                    'File "%s" already exists in folder. Upload cancelled.',
                    $filename
                ), 409);
            }

            // Upload to FAL (D4: use addFile for temp file, not addUploadedFile)
            // addUploadedFile expects UploadedFileInterface which we've already moved
            $file = $storage->addFile($tempPath, $folderObject, $filename, DuplicationBehavior::CANCEL);
        } catch (\TYPO3\CMS\Core\Resource\Exception\ExistingTargetFileNameException $e) {
            return $this->jsonError('File already exists: ' . $e->getMessage(), 409);
        } catch (\Exception $e) {
            return $this->jsonError('Upload failed: ' . $e->getMessage(), 500);
        } finally {
            if (file_exists($tempPath)) {
                @unlink($tempPath);
            }
        }

        // Extract metadata (width/height) and generate preview — non-critical enrichment.
        // Must run AFTER the try/finally: the file is already in FAL, so extractor failures
        // must not abort the upload response.
        try {
            $indexer = GeneralUtility::makeInstance(Indexer::class, $storage);
            $indexer->extractMetaData($file);

            if (str_starts_with($file->getMimeType(), 'image/')) {
                $file->process(ProcessedFile::CONTEXT_IMAGEPREVIEW, []);
            }
        } catch (\Exception) {
            // Metadata extraction and preview generation are non-critical
        }

        // Build success response
        $publicUrl = $file->getPublicUrl() ?? '(not public)';

        $responseData = [
            'success' => true,
            'file' => [
                'uid' => $file->getUid(),
                'name' => $file->getName(),
                'size' => $file->getSize(),
                'mimeType' => $file->getMimeType(),
                'path' => $storage->getUid() . ':' . $file->getIdentifier(),
                'url' => $publicUrl,
            ],
        ];

        return $this->jsonSuccess($responseData);
    }

    /**
     * Extract Bearer token from Authorization header
     *
     * Checks multiple sources because Apache may strip the Authorization header
     * and pass it via HTTP_AUTHORIZATION or REDIRECT_HTTP_AUTHORIZATION instead.
     */
    private function extractBearerToken(ServerRequestInterface $request): ?string
    {
        // Try PSR-7 header first (standard way)
        $authHeader = $request->getHeaderLine('Authorization');

        // If not found, check server params (Apache passthrough via .htaccess)
        if (empty($authHeader)) {
            $serverParams = $request->getServerParams();
            $authHeader = $serverParams['HTTP_AUTHORIZATION']
                ?? $serverParams['REDIRECT_HTTP_AUTHORIZATION']
                ?? '';
        }

        if (empty($authHeader)) {
            return null;
        }

        if (preg_match('/^Bearer\s+(.+)$/i', $authHeader, $matches)) {
            return $matches[1];
        }

        return null;
    }

    /**
     * Atomically consume a token (mark as used)
     *
     * @return array|null Token data if successful, null if token invalid/expired/used
     */
    private function consumeToken(string $tokenHash): ?array
    {
        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('tx_mcpserver_upload_tokens');

        // Atomic update: only succeeds if token exists, not used, not expired
        $affectedRows = $connection->executeStatement(
            'UPDATE tx_mcpserver_upload_tokens SET used = 1 WHERE token_hash = ? AND used = 0 AND expires_at > ?',
            [$tokenHash, time()]
        );

        if ($affectedRows !== 1) {
            return null;
        }

        // Fetch the token data
        $tokenData = $connection->executeQuery(
            'SELECT * FROM tx_mcpserver_upload_tokens WHERE token_hash = ?',
            [$tokenHash]
        )->fetchAssociative();

        return $tokenData ?: null;
    }

    /**
     * Check if BE user is still active (not disabled, not deleted)
     */
    private function isUserActive(int $userId): bool
    {
        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('be_users');

        $user = $connection->executeQuery(
            'SELECT uid FROM be_users WHERE uid = ? AND disable = 0 AND deleted = 0',
            [$userId]
        )->fetchAssociative();

        return $user !== false;
    }

    /**
     * Set up backend user context (copied from McpEndpoint pattern)
     */
    private function setupBackendUserContext(int $userId): void
    {
        $beUser = GeneralUtility::makeInstance(BackendUserAuthentication::class);

        $connection = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getConnectionForTable('be_users');

        $queryBuilder = $connection->createQueryBuilder();
        $userData = $queryBuilder
            ->select('*')
            ->from('be_users')
            ->where($queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter($userId)))
            ->executeQuery()
            ->fetchAssociative();

        if ($userData) {
            $beUser->user = $userData;
            $GLOBALS['BE_USER'] = $beUser;

            $beUser->fetchGroupData();

            // Initialize language service
            $languageServiceFactory = GeneralUtility::makeInstance(LanguageServiceFactory::class);
            $languageService = $languageServiceFactory->createFromUserPreferences($beUser);
            $GLOBALS['LANG'] = $languageService;

            // Set up workspace context
            $workspaceService = GeneralUtility::makeInstance(WorkspaceContextService::class);
            $workspaceId = $workspaceService->switchToOptimalWorkspace($beUser);

            // Set up TYPO3 Context API
            $context = GeneralUtility::makeInstance(Context::class);
            $context->setAspect('backend.user', new UserAspect($beUser));
            $context->setAspect('workspace', new WorkspaceAspect($workspaceId));
        }

        // Ensure TCA is loaded
        $tcaFactory = GeneralUtility::getContainer()->get(\TYPO3\CMS\Core\Configuration\Tca\TcaFactory::class);
        $GLOBALS['TCA'] = $tcaFactory->get();
    }

    /**
     * Handle PHP upload errors with user-friendly messages
     */
    private function handleUploadError(int $errorCode): ResponseInterface
    {
        $message = match ($errorCode) {
            UPLOAD_ERR_INI_SIZE => 'File exceeds PHP upload_max_filesize limit. Check server configuration.',
            UPLOAD_ERR_FORM_SIZE => 'File exceeds form MAX_FILE_SIZE directive.',
            UPLOAD_ERR_PARTIAL => 'File was only partially uploaded. Please retry.',
            UPLOAD_ERR_NO_FILE => 'No file was uploaded.',
            UPLOAD_ERR_NO_TMP_DIR => 'Server misconfiguration: missing temp directory.',
            UPLOAD_ERR_CANT_WRITE => 'Server error: failed to write file to disk.',
            UPLOAD_ERR_EXTENSION => 'Upload blocked by PHP extension.',
            default => 'Unknown upload error: ' . $errorCode,
        };

        $statusCode = match ($errorCode) {
            UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE => 413,
            UPLOAD_ERR_PARTIAL => 400,
            default => 400,
        };

        return $this->jsonError($message, $statusCode);
    }

    /**
     * Get allowed file extensions from storage configuration
     *
     * @return array|null Array of extensions or null if all allowed
     */
    private function getAllowedExtensions($storage): ?array
    {
        // TYPO3 storage has file_extensions configuration
        $configuration = $storage->getConfiguration();

        if (empty($configuration['fileExtensions']) || $configuration['fileExtensions'] === '*') {
            return null; // All extensions allowed
        }

        return GeneralUtility::trimExplode(',', $configuration['fileExtensions'], true);
    }

    /**
     * Detect MIME type of uploaded file
     */
    private function detectMimeType(UploadedFileInterface $uploadedFile): string
    {
        // Try to get from file content using finfo
        $stream = $uploadedFile->getStream();
        $content = $stream->read(8192); // Read first 8KB for detection
        $stream->rewind();

        $finfo = new \finfo(FILEINFO_MIME_TYPE);
        $mimeType = $finfo->buffer($content);

        return $mimeType ?: 'application/octet-stream';
    }

    /**
     * Check if detected MIME type is reasonable for file extension
     */
    private function isMimeTypeAllowedForExtension(string $mimeType, string $extension): bool
    {
        // Map of extensions to allowed MIME type patterns
        $allowedMimeTypes = [
            'jpg' => ['image/jpeg'],
            'jpeg' => ['image/jpeg'],
            'png' => ['image/png'],
            'gif' => ['image/gif'],
            'webp' => ['image/webp'],
            'svg' => ['image/svg+xml', 'text/xml', 'application/xml', 'text/plain'],
            'pdf' => ['application/pdf'],
            'doc' => ['application/msword', 'application/octet-stream'],
            'docx' => ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip'],
            'xls' => ['application/vnd.ms-excel', 'application/octet-stream'],
            'xlsx' => ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'],
            'txt' => ['text/plain'],
            'csv' => ['text/csv', 'text/plain', 'application/csv'],
            'zip' => ['application/zip', 'application/x-zip-compressed'],
            'mp4' => ['video/mp4'],
            'mp3' => ['audio/mpeg'],
        ];

        // If we don't have rules for this extension, allow it
        if (!isset($allowedMimeTypes[$extension])) {
            return true;
        }

        return in_array($mimeType, $allowedMimeTypes[$extension], true);
    }

    /**
     * Sanitize SVG file to remove malicious content
     */
    private function sanitizeSvgUpload(UploadedFileInterface $uploadedFile): void
    {
        $sanitizer = GeneralUtility::makeInstance(SvgSanitizer::class);

        // Read SVG content
        $stream = $uploadedFile->getStream();
        $svgContent = $stream->getContents();
        $stream->rewind();

        // Sanitize
        $sanitizedContent = $sanitizer->sanitizeContent($svgContent);

        // We can't modify the uploaded file in place, but the sanitization
        // is primarily a check - TYPO3's addFile will run sanitization again
        // during the actual file processing.
    }

    /**
     * Return JSON success response
     */
    private function jsonSuccess(array $data): ResponseInterface
    {
        $stream = new Stream('php://temp', 'rw');
        $stream->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
        $stream->rewind();

        $response = new Response($stream, 200, ['Content-Type' => 'application/json']);
        return $this->addCorsHeaders($response);
    }

    /**
     * Return JSON error response
     */
    private function jsonError(string $message, int $status): ResponseInterface
    {
        $stream = new Stream('php://temp', 'rw');
        $stream->write(json_encode([
            'success' => false,
            'error' => $message,
        ], JSON_UNESCAPED_SLASHES));
        $stream->rewind();

        $response = new Response($stream, $status, ['Content-Type' => 'application/json']);
        return $this->addCorsHeaders($response);
    }
}
